CREATE TABLE IF NOT EXISTS  users (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    login  varchar(30) NOT NULL UNIQUE,
    email varchar(30) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,

    dateCreate date DEFAULT CURRENT_DATE NOT NULL,
    dateUpdate date,
    dateRemove date
);

CREATE TABLE IF NOT EXISTS posts (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    title  varchar(30) NOT NULL,
    content text NOT NULL,
    image varchar(100),
    viewsCount int NOT NULL DEFAULT 0,
    likes int NOT NULL DEFAULT 0,
    authorId int references users NOT NULL ,

    dateCreate date DEFAULT CURRENT_DATE NOT NULL,
    dateUpdate date,
    dateRemove date,

    FOREIGN KEY (authorId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS tokens (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    value varchar(255) UNIQUE,
    userId int REFERENCES users NOT NULL,
    dateCreate date DEFAULT CURRENT_DATE,

    FOREIGN KEY(userId) REFERENCES users (id)
);

CREATE UNIQUE INDEX tokenIndex ON tokens (value);



